=== GamingPlatformFrameworksFall2015-WHK/Raven2015/Raven2015/Resources/XML/assets.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT ASSETS (Textures, Music, Sounds, Fonts, Levels, Animations, Renderables)>
  <!ELEMENT Textures (TextureFilePath*)>
    <!ELEMENT TextureFilePath (#PCDATA)>
  <!ELEMENT Music (MusicFilePath*)>
    <!ELEMENT MusicFilePath (#PCDATA)>
  <!ELEMENT Sounds (SoundFilePath*)>
    <!ELEMENT SoundFilePath (#PCDATA)>
  <!ELEMENT Fonts (FontFilePath*)>
    <!ELEMENT FontFilePath (#PCDATA)>
  <!ELEMENT Levels (LevelFilePath+)>
    <!ELEMENT LevelFilePath (#PCDATA)>
  <!ELEMENT Animations (Animation*)>
    <!ELEMENT Animation (AnimationTextureFilePath, FrameCount, FrameWidth, FrameHeight, AnimationSpeed, IsLooping)>
      <!ATTLIST Animation Name CDATA #REQUIRED>
      <!ELEMENT AnimationTextureFilePath (#PCDATA)>
      <!ELEMENT FrameCount (#PCDATA)>
      <!ELEMENT FrameWidth (#PCDATA)>
      <!ELEMENT FrameHeight (#PCDATA)>
      <!ELEMENT AnimationSpeed (#PCDATA)>
      <!ELEMENT IsLooping (#PCDATA)>
  <!ELEMENT Renderables (RenderableTexts, RenderableRectangles, RenderableCircles, RenderableSprites)>
    <!ELEMENT RenderableTexts (RenderableText*)>
      <!ELEMENT RenderableText (RenderableTextRenderLayer, RenderableTextRenderPriority, RenderableTextTextContent, FontFilePath)>
        <!ATTLIST RenderableText Name CDATA #REQUIRED>
        <!ELEMENT RenderableTextRenderLayer (#PCDATA)>
        <!ELEMENT RenderableTextRenderPriority (#PCDATA)>
        <!ELEMENT RenderableTextTextContent (#PCDATA)>
        <!ELEMENT RenderableTextFontFilePath (#PCDATA)>
    <!ELEMENT RenderableRectangles (RenderableRectangle*)>
      <!ELEMENT RenderableRectangle (RenderableRectangleRenderLayer, RenderableRectangleRenderPriority)>
        <!ATTLIST RenderableRectangle Name CDATA #REQUIRED>
        <!ELEMENT RenderableRectangleRenderLayer (#PCDATA)>
        <!ELEMENT RenderableRectangleRenderPriority (#PCDATA)>
    <!ELEMENT RenderableCircles (RenderableCircle*)>
      <!ELEMENT RenderableCircle (RenderableCircleRenderLayer, RenderableCircleRenderPriority)>
        <!ATTLIST RenderableCircle Name CDATA #REQUIRED>
        <!ELEMENT RenderableCircleRenderLayer (#PCDATA)>
        <!ELEMENT RenderableCircleRenderPriority (#PCDATA)>
    <!ELEMENT RenderableSprites (RenderableSprite*)>
      <!ELEMENT RenderableSprite (RenderableSpriteRenderLayer, RenderableSpriteRenderPriority, RenderableSpriteTextureFilePath, RenderableSpriteAnimationName)>
        <!ATTLIST RenderableSprite Name CDATA #REQUIRED>
        <!ELEMENT RenderableSpriteRenderLayer (#PCDATA)>
        <!ELEMENT RenderableSpriteRenderPriority (#PCDATA)>
        <!ELEMENT RenderableSpriteTextureFilePath (#PCDATA)>
        <!ELEMENT RenderableSpriteAnimationName (#PCDATA)>

=== GamingPlatformFrameworksFall2015-WHK/Raven2015/Raven2015/Resources/XML/assets.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ASSETS SYSTEM "assets.dtd">
<ASSETS>
    <Textures/>
    <Music/>
    <Sounds/>
    <Fonts/>
    <Levels>
      <LevelFilePath>Resources/XML/DefaultLevel.xml</LevelFilePath>
    </Levels>
    <Animations/>
    <Renderables>
        <RenderableTexts/>
        <RenderableRectangles/>
        <RenderableCircles/>
        <RenderableSprites/>
    </Renderables>
</ASSETS>
